### ISSUE TITLE
Proposal: 2nd generation CLI runtime architecture

### ISSUE THREAD

**Issue by ncoghlan** [leapp-to/leapp#127]
https://github.com/leapp-to/prototype/issues/126 covers some proposed changes to the way we *develop* LeApp to better separate the deployable components (the CLI and Cockpit plugin) from the integration tests and demo environment for those components.

This proposal instead covers some suggestions for significant structural changes to the LeApp CLI itself.

Key assumption: while it may connect to RHEL/CentOS 6 systems remotely, LeApp itself will always run on RHEL/CentOS 7 or Fedora.

1. To allow for backend independent status caching, switch to a client/server `leappctl`/`leappd` architecture based on Unix domain sockets:

- `leappd` would be an AF_UNIX socket-activated Flask service running under gunicorn (http://docs.gunicorn.org/en/stable/deploy.html#systemd)
- the `leappctl` CLI would communicate with the backend using https://pypi.python.org/pypi/requests-unixsocket
- the Cockpit plugin would communicate with leappd using either the CLI `cockpit.spawn()` (as it does now) or else cockpit.http() (which supports unix sockets by omitting the scheme and host parts of the connection URL) to communicate with `leappd` directly

This HTTP-over-a-Unix-socket approach would supersede the previous proposal in https://github.com/leapp-to/prototype/issues/7 to use DBus for communication with a status caching backend.

At some future date we may decide it makes sense to expose `leappd` as a network accessible API, but at least initially, it would purely be a status and capability caching service for `leappctl` and the Cockpit plugin

2. The initial version of `leappd` would support two kinds of environment:

- Simulated: source and target environment simulated based on canned data
- LocalVagrant: local Vagrant machines used as both source and target environment

3. The initial version of `leappd` would support one migration technique:

- Macrocontainer: the entire original VM (except the kernel) is migrated as a mutable persistent volume

**Comment by vinzenz** [comment]
About 3. we actually we might be able to start support pseudo macro containers pretty soon - I am very close to something usable.

**Comment by shaded-enmity** [comment]
Like the proposal in overall, I'll just sprinkle my thoughts here -

The client/server split will essentially make LeApp an API-first project - the CLI, being a thin wrapper for communicating with the server, will only be able to do as much as using the exposed APIs, so we probably want to use something like Swagger to document & keep track of our REST endpoints.

Secondly, in order to prevent bad things from happening, I'd suggest implementing the server and client in *different* languages, which will only further emphasize the API-first aspect - instead of taking shortcuts and saying `from leapp.private.functionality import ApiDoesntExposeThis` in the CLI code we'll be forced to tackle these issues head on. This won't be for *free* though, we'll need to express the same data models in 2 distinct languages, but that should be well within range of Swagger's code generation capabilities. The split will also allow us to try out (in the future) formal methods to verify the semantics of the API - I've been exploring [Leslie Lamport's TLA+](https://github.com/tlaplus/tlaplus) recently and it seems to be a good fit for this. API verification is rather hot topic and this might pave a road for a lot of future work.

Thirdly, while I'd love for the second language to be Rust I think the safest way to Go...  would be Go -  
we've got some experience with Go already in the team (me and @vinzenz - hell, one of my Go projects is even in production nowadays)  and people who don't know Go expressed their interest in learning it. 

With that being said, I'd like to propose that the server part of LeApp be written in Go - we'll get (almost) statically linked, native binary with runtime zero dependencies and minimal footprint (GC I'm *looking* at you), which to me sounds much better for a system daemon running in the background.

/cc @vmindru @mfranczy @GAZDOWN
