### ISSUE TITLE
false positive ports discovered on target machine

### ISSUE THREAD

**Issue by vmindru** [leapp-to/leapp#238]
actual ports on the system

[listening_ports](http://imgur.com/mpNrphh)

vs

[discovered_ports](http://imgur.com/Zvi0wnz)

**Comment by mfranczy** [comment]
I wouldn't say it's false positive, since docker as default binds ports to ```:::``` we need all informations about used ports, not only in ```LISTEN``` status. For example when you have firefox session open you will have a lot of  ports in ```ESTABLISHED``` state and docker will not be able to bind the same ports used by browser. That's why I think we need this info to prevent conflicts.

The question is should we change the default network conf for docker to avoid binds to any interface?

**Comment by vmindru** [comment]
this is very strange, one should really not block binding for a listening incoming connection, i wonder what is the diff between source bind for SSH and WEECHAT going to do some investigation. 
http://imgur.com/a/p6x89 

any way I really think that we should report only listening busy ports and not ESTABLISHED, ESTABLISHED are ephemeral and going to disappear after end of TCP connection and not likely to bind anytime soon again, this would be very confusing for sysadmins. 

VM

**Comment by mfranczy** [comment]
Ok, however what if we have persistent connection between to applications? We don't know the time and we can't assume it will take only 5 minutes and the next port binding will be random (I mean it depends on how tcp communication is implemented on given app).

**Comment by vmindru** [comment]
https://github.com/leapp-to/leapp/pull/247 will workaround this

**Comment by mfranczy** [comment]
Card from trello: https://trello.com/c/ZDzdTA2u/173-group-busy-ports-by-state-on-a-target-machine-to-avoid-sys-admin-confusion
