### ISSUE TITLE
Port discovery should be done via netstat from within the source not via nmap from the outside

### ISSUE THREAD

**Issue by vinzenz** [leapp-to/leapp#68]
Currently we're attempting to implement the port discovery via nmap from the outside

This is a fast gain for the prototype but eventually should be moved to a proper discovery inside of the source, with a tool like netstat.

**Comment by ncoghlan** [comment]
Is that necessarily the case? We'd like the migration to require as few modifications to the source system as possible, so when there are things we can discover from outside the machine (such as which ports are open), it seems desirable to do that, rather than rely on particular tools being present on the system to be migrated.

**Comment by vmindru** [comment]
Hi Nick, 

nmap does not have to be present this info is available in /proc if netstat is not present,  this is would be a noninvasive method, just read facts. 

VM

**Comment by vinzenz** [comment]
Also using netlink might be another way to talk to the kernel about this (Just adding a thought here)

**Comment by shaded-enmity** [comment]
I'd still keep `nmap` as an option for people who go by "forget about running any code on my nodes", especially since the output of netstat reports much more data then just `nmap`. I actually like to think about them as complementary - `netstat` will show even non exposed ports, while `nmap` will list externally reachable endpoints.

Don't throw the baby away with the water :)
